## [특강] Numpy, Pandas, Matplotlib

### 1. Numpy: 고속 연산, 슬라이싱 및 차원 제어
#### 1.1 명시적 타입 배열 생성과 다차원 슬라이싱

배열(Array)
- 메모리상에 연속된 구조, 인덱스 연산자([]) 접근 가능
- 동일한 자료형으로 데이터가 구성
- c언어 개발(직접 메모리 접근)
- dtpye: 자료형 명시(ex: np.int64, np.float64)

In [1]:
# Numpy
import numpy as np

nums = np.array([10, 20, 30])       # 붙어있는 구조의 배열 (리스트x)
nums

array([10, 20, 30])

In [2]:
import numpy as np

nums = np.array([10, 20, 30], dtype=np.float64)       # 자료형 명시
nums

array([10., 20., 30.])

In [3]:
nums[0]     # 숫자만 기록 가능, 문자는 지양(가능은 함)

np.float64(10.0)

In [4]:
# 2차원 배열(Matrix)
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])      

matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# 배열 선택, 슬라이싱
- matrix[행, 열]
- matrix[0:2, 1:3] : 행은 0, 1, 열은 1, 2
- matrix[:, 0] : 모든 행의 0번째 열
    ㄴmatrix[1:, :2] -> 행은 1번 인덱스부터 전체, 열은 1번 인덱스 이하

In [5]:
# matrix[행, 열]
print("0행 2열:", matrix[0][2], matrix[0,2])

0행 2열: 30 30


In [6]:
# matrix 지정 출력
print(matrix[0:2, 1:3])

[[20 30]
 [50 60]]


In [7]:
# matrix 0행 전체 출력
print(matrix[:, 0])

[10 40 70]


In [8]:
# matrix 
print(matrix[1:, :2])

[[40 50]
 [70 80]]


#### 1.2 차원 변경(reshape, flatten)과 축(Axis)

reshape(행, 열) / flatten()

- reshape(행, 열) : 1차원 배열 -> 지정된 행과 열 구조로 차원수 변경, -1 : 자동 결정
- arange(시작, 종료, 증감) -> 시작 이상 종료 미만으로 숫자 생성
- flatten() : 2차원 배열 -> 1차원으로 평탄화, 연산에 특화

In [9]:
# reshape(행, 열)
arr = np.arange(1, 13)  # 1~12

mat_3x4 = arr.reshape(3, 4)
print(mat_3x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
# 자동 결정
# mat_3x4 = arr.reshape(3, -1)        
mat_3x4 = arr.reshape(-1, 4)
print(mat_3x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
# flatten() 
flat_arr = mat_3x4.flatten()
print(flat_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


축(axis)

2차원 배열에서 연산의 방향을 설정
- axis : 0 -> 행기준에서 연산
- axis : 1 -> 열기준에서 연산

In [12]:
mat = np.arange(1, 7).reshape(2, -1)

print(mat, "\n")

sum_axis0 = mat.sum(axis=0)
sum_axis1 = mat.sum(axis=1)

print("행 기준 합계:", sum_axis0)
print("열 기준 합계:", sum_axis1)

[[1 2 3]
 [4 5 6]] 

행 기준 합계: [5 7 9]
열 기준 합계: [ 6 15]


#### 1.3 Numpy 브로드캐스팅(Broadcasting) 연산

연산을 알아서 전체 행열에 동일한 값으로 연산 실행

In [13]:
mat = np.array([
    [10,20,30],
    [40,50,60]
])

print("곱하기", mat * 5, "\n")
print("더하기", mat + 5)

곱하기 [[ 50 100 150]
 [200 250 300]] 

더하기 [[15 25 35]
 [45 55 65]]


In [14]:
# 각각 배열 단위로 덧셈, 곱셈 가능
vec = np.array([1,2,3])

mat + vec

array([[11, 22, 33],
       [41, 52, 63]])

#### 1.4 행렬 전치(Transpose) 및 행렬곱(@)

- 객체.transpose() : {행, 열} -> (열, 행) / 전치
- 객체.T : 객체.transpose() 간략 버전
- 행렬 곱 연산(@) : 

In [ ]:
# 객체.transpose()
mat = np.array([
    [1,2,3],
    [4,5,6]
])

print(mat, "\n")
print("전치 행렬:\n", mat.transpose())

[[1 2 3]
 [4 5 6]] 

전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 객체.T
mat = np.array([
    [1,2,3],
    [4,5,6]
])

print(mat, "\n")
print("전치 행렬:\n", mat.T)

[[1 2 3]
 [4 5 6]] 

전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]


In [18]:
# 행렬 곱 연산(@)
mat1 = np.array([
    [10,20],
    [30,40]
])
mat2 = np.array([
    [1,2],
    [3,4]
])

mat3 = mat1 @ mat2

mat3

array([[ 70, 100],
       [150, 220]])